name: Get YouTube Live to m3u8
on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get 中視新聞.m3u8
      run: |
        touch ./CTVNews.m3u8
        sudo cat >./CTVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=TCnaIE_SAtM)
        EOL

    - name: Get 台視新聞.m3u8
      run: |
        touch ./TTVNews.m3u8
        sudo cat >./TTVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL

    # - name: Get 公共電視.m3u8
    #   run: |
    #     touch ./公共電視.m3u8
    #     sudo cat >./公共電視.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=C6gYqSHLRw4)
    #     EOL

    - name: Get 東森財經新聞.m3u8
      run: |
        touch ./EBCFinancialNews.m3u8
        sudo cat >./EBCFinancialNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=WHEPzbFA3hw)
        EOL

    - name: Get 東森新聞.m3u8
      run: |
        touch ./EBCNews.m3u8
        sudo cat >./EBCNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/c/newsebc/live)
        EOL

    # - name: Get 中天新聞.m3u8
    #   run: |
    #     touch ./中天新聞.m3u8
    #     sudo cat >./中天新聞.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=oIgbl7t0S_w)
    #     EOL

    - name: Get 寰宇新聞.m3u8
      run: |
        touch ./GlobalNewsTV.m3u8
        sudo cat >./GlobalNewsTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=6IquAgfvYmc)
        EOL

    - name: Get 寰宇新聞台灣台.m3u8
      run: |
        touch ./GlobalNewsTVTW.m3u8
        sudo cat >./GlobalNewsTVTW.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=w87VGpgd90U)
        EOL

    - name: Get 三立News+.m3u8
      run: |
        touch ./SETNewsPlus.m3u8
        sudo cat >./SETNewsPlus.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=oZdzzvxTfUY)
        EOL

    - name: Get 三立iNews.m3u8
      run: |
        touch ./SETiNews.m3u8
        sudo cat >./SETiNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=CKjSm5ZeehE)
        EOL

    - name: Get TVBS新聞.m3u8
      run: |
        touch ./TVBSNews.m3u8
        sudo cat >./TVBSNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=m_dhMSvUCIc)
        EOL

    - name: Get 鏡新聞.m3u8
      run: |
        touch ./MNews.m3u8
        sudo cat >./MNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g "https://www.youtube.com/channel/UC4LjkybVKXCDlneVXlKAbmw/live")
        EOL

    - name: Get 東森幼幼台.m3u8
      run: |
        touch ./YOYOTVEBC.m3u8
        sudo cat >./YOYOTVEBC.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/c/yoyotvebc/live)
        EOL

    # - name: Get KPOPLive.m3u8
    #   run: |
    #     touch ./KPOPLive.m3u8
    #     sudo cat >./KPOPLive.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/channel/UCPde4guD9yFBRzkxk2PatoA/live)
    #     EOL

    # - name: Get KKBOX.m3u8
    #   run: |
    #     touch ./KKBOX.m3u8
    #     sudo cat >./KKBOX.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g http://www.youtube.com/channel/UCh3S2zaqmyQX2dMwpi63zSA/live)
    #     EOL

    # - name: Get KPOP.m3u8
    #   run: |
    #     touch ./KPOP.m3u8
    #     sudo cat >./KPOP.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/channel/UCoRXPcv8XK5fAplLbk9PTww/live)
    #     EOL

    - name: Get 大愛一台.m3u8
      run: |
        touch ./DaAi_1.m3u8
        sudo cat >./DaAi_1.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=MIqUplvSRWA)
        EOL

    - name: Get 大愛二台.m3u8
      run: |
        touch ./DaAi_2.m3u8
        sudo cat >./DaAi_2.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=DTNkEm6jaqQ)
        EOL

    # - name: Get 大愛三台.m3u8
    #   run: |
    #     touch ./大愛三台.m3u8
    #     sudo cat >./大愛三台.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=MIqUplvSRWA)
    #     EOL

    - name: Get 德國之聲新聞.m3u8
      run: |
        touch ./DWNews.m3u8
        sudo cat >./DWNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=6HodCcEW_oQ)
        EOL

    - name: Get FoxNews.m3u8
      run: |
        touch ./FoxNews.m3u8
        sudo cat >./FoxNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=YDfiTGGPYCk)
        EOL

    - name: Get BloombergNews.m3u8
      run: |
        touch ./BloombergNews.m3u8
        sudo cat >./BloombergNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=iyOq8DhaMYw)
        EOL

    - name: Get Arirang.m3u8
      run: |
        touch ./Arirang.m3u8
        sudo cat >./Arirang.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(yt-dlp -g https://www.youtube.com/watch?v=CJVBX7KI5nU)
        EOL

    - name: Get 晋江电视.m3u8
      run: |
        touch ./JinjiangTV.m3u8
        sudo cat >./JinjiangTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(curl -s http://www.jinjiang.tv/m2o/channel/channel_info.php?id=4 | sed 's#\\##g;s#"#\n#g' | grep 'http.*live')
        EOL

    # - name: Get 以家人之名.m3u8
    #   run: |
    #     touch ./以家人之名.m3u8
    #     sudo cat >./以家人之名.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=0dchv4MPOWA)
    #     EOL

    # - name: Get 琅琊榜.m3u8
    #   run: |
    #     touch ./琅琊榜.m3u8
    #     sudo cat >./琅琊榜.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/live/_MOhQbKegXs)
    #     EOL

    # - name: Get 知否知否應是綠肥紅瘦.m3u8
    #   run: |
    #     touch ./知否知否應是綠肥紅瘦.m3u8
    #     sudo cat >./知否知否應是綠肥紅瘦.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=iZxJDOqg_E0)
    #     EOL

    # - name: Get 步步驚心.m3u8
    #   run: |
    #     touch ./步步驚心.m3u8
    #     sudo cat >./步步驚心.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=0jwzYLZF9AI)
    #     EOL

    # - name: Get 公主小妹.m3u8
    #   run: |
    #     touch ./公主小妹.m3u8
    #     sudo cat >./公主小妹.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=lz7WqYKTpo4)
    #     EOL

    # - name: Get 犀利人妻.m3u8
    #   run: |
    #     touch ./犀利人妻.m3u8
    #     sudo cat >./犀利人妻.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=HRwAMooYM3w)
    #     EOL

    # - name: Get 小資女孩向前衝.m3u8
    #   run: |
    #     touch ./小資女孩向前衝.m3u8
    #     sudo cat >./小資女孩向前衝.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=Il3YPiaW24Q)
    #     EOL

    # - name: Get 我的自由年代.m3u8
    #   run: |
    #     touch ./我的自由年代.m3u8
    #     sudo cat >./我的自由年代.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/watch?v=VM4Qrlcgq0U)
    #     EOL

    # - name: Get 飢餓遊戲.m3u8
    #   run: |
    #     touch ./飢餓遊戲.m3u8
    #     sudo cat >./飢餓遊戲.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/channel/UCriy3vlLtiBov3nLdPLadUg/live)
    #     EOL

    # - name: Get 綜藝玩很大.m3u8
    #   run: |
    #     touch ./綜藝玩很大.m3u8
    #     sudo cat >./綜藝玩很大.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/channel/UCQU5uVTG8h9LToACKrm1LMA/live)
    #     EOL

    # - name: Get 天才衝衝衝.m3u8
    #   run: |
    #     touch ./天才衝衝衝.m3u8
    #     sudo cat >./天才衝衝衝.m3u8 <<EOL
    #     #EXTM3U
    #     #EXT-X-VERSION:3
    #     #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
    #     $(yt-dlp -g https://www.youtube.com/channel/UCdpxNQgqL3276yjrK03gMXA/live)
    #     EOL

    - name: Get 民視.m3u8
      run: |
        touch ./FTV.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FTV | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 民視第一台.m3u8
      run: |
        touch ./FMTV.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FMTV | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FMTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 民視台灣台.m3u8
      run: |
        touch ./FTTV.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FTTV | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FTTV.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 民視新聞台.m3u8
      run: |
        touch ./FTVNews.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FTVNews | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FTVNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 民視影劇台.m3u8
      run: |
        touch ./FTVDrama.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FTVDrama | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FTVDrama.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 民視綜藝台.m3u8
      run: |
        touch ./FTVVariety.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FTVVariety | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FTVVariety.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 民視旅遊台.m3u8
      run: |
        touch ./FTVTravel.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=FTVTravel | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./FTVTravel.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 華視.m3u8
      run: |
        touch ./CTS.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=CTS | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./CTS.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    - name: Get 華視新聞.m3u8
      run: |
        touch ./CTSNews.m3u8
        var1=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" -k https://app.4gtv.tv/Data/GetChannelURL_Mozai.ashx?ChannelName=CTSNews | awk -F\" '{print $6}')
        var2=$(curl --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" $var1 | sed -n '8p' | awk -F\. '{print $1}')
        sudo cat >./CTSNews.m3u8 <<EOL
        #EXTM3U
        #EXT-X-VERSION:3
        #EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=2560000
        $(echo $var1 | sed "s/master/$var2/")
        EOL

    # - name : Upload artifact
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: YTlive m3u8
    #     path: .

    - name : Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: YTlive m3u8
        path: .


    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
